import type { AppLanguage } from "../types/settings";

const copy = {
  ru: {
    overlay: {
      eyebrow: "AI Presence Layer",
      modeIdle: "Idle shell",
      summary:
        "Базовый overlay уже поднят. Следующий крупный блок по порядку: secure settings, audio pipeline и Realtime session.",
      hudTitle: "JARVIS // SPEAKING OVERLAY",
      hudSubtitle: "СИСТЕМЫ ОНЛАЙН",
      wakeWordLabel: "Wake phrase",
      addressLabel: "Обращение",
      openSettings: "Открыть настройки",
      nextPhase: "Realtime: next phase",
      activateVoice: "Активировать голос",
      pauseVoice: "Сбросить сессию",
      badgeVoiceLock: "VOICE LOCK",
      badgeLowLatency: "LOW LATENCY",
      badgeMicRequired: "MIC MONITOR",
      badgeSearchReady: "WEB SEARCH READY",
      badgeSecureKeyPending: "SECURE KEY PENDING",
      devIdle: "Idle",
      devListening: "Listening",
      devThinking: "Thinking",
      devSpeaking: "Speaking",
      devReset: "Reset",
      devMicOn: "Mic on",
      devMicOff: "Mic off",
      stateBadge: {
        idle: "IDLE",
        listening: "LISTENING",
        thinking: "THINKING",
        speaking: "SPEAKING",
      },
      statePanels: {
        idle: {
          label: "Overlay state",
          headline: "Standby presence",
          meta: "Awaiting wake phrase or manual activation",
          description: "HUD remains calm, breathing lightly, and waits for a wake event.",
        },
        listening: {
          label: "Overlay state",
          headline: "Listening for voice input",
          meta: "Microphone analyser is driving the waveform in real time",
          description: "Speak into the microphone. After a short silence, the HUD advances to analysis.",
        },
        thinking: {
          label: "Overlay state",
          headline: "Parsing intent",
          meta: "Transitioning from capture to response synthesis",
          description: "The mask tightens, contours scan, and the assistant holds the turn briefly.",
        },
        speaking: {
          label: "Overlay state",
          headline: "Response presence active",
          meta: "Mask intensity and wave energy increase in speaking mode",
          description: "This state is ready for the future output-audio binding from the realtime session.",
        },
      },
      statusFoundationTitle: "Foundation scaffold",
      statusFoundationDetail: "Tauri 2 + React TS skeleton initialized.",
      statusSettingsTitle: "Settings window",
      statusSettingsDetail: "Programmatic secondary window is wired from Rust.",
      statusKeyTitle: "Secure key storage",
      statusKeyReady: "OpenAI API key is stored in native secure storage.",
      statusKeyPending: "Windows Credential Manager wiring exists, but no key is stored yet.",
      statusRealtimeTitle: "Realtime voice loop",
      statusRealtimePending: "WebRTC session flow is the next major integration step.",
    },
    settings: {
      eyebrow: "Configuration / Phase 2",
      title: "JARVIS Control Room",
      summary:
        "Настройки уже сохраняются на native side. Следующий слой по порядку: devices, Realtime session и wake engine.",
      modeChip: "Windows-first",
      profileTitle: "Primary profile",
      profileSummary:
        "Эти поля теперь сохраняются между запусками. API key пишется в secure storage и не возвращается в renderer.",
      languageLabel: "Язык интерфейса",
      languageRussian: "Русский",
      wakeWordLabel: "Wake word",
      addressLabel: "Обращение к пользователю",
      apiKeyLabel: "OpenAI API key",
      apiKeyPlaceholder: "Вставьте ключ для сохранения в secure storage",
      inlineNote:
        "Сейчас уже сохраняются язык, wake word и обращение. Проверка ключа через API и device settings будут следующими шагами.",
      apiKeyStored: "API key уже сохранен в Windows secure storage.",
      apiKeyMissing: "API key еще не сохранен.",
      saveButton: "Сохранить настройки",
      closeButton: "Закрыть окно",
      executionTitle: "Execution status",
      executionSummary: "Ниже отмечено, что уже сделано по foundation и packaging.",
      checklistFoundationTitle: "Tauri desktop scaffold",
      checklistFoundationDetail: "Workspace now contains the first bootable desktop app shell.",
      checklistOverlayTitle: "Separate overlay window",
      checklistOverlayDetail: "Overlay is configured as the main transparent always-on-top window.",
      checklistSettingsTitle: "Separate settings window",
      checklistSettingsDetail: "Settings window is created from Rust and can be focused on demand.",
      checklistTrayTitle: "Tray icon skeleton",
      checklistTrayDetail: "Native tray menu is wired with overlay, settings and quit actions.",
      checklistPackagingTitle: "Production package validation",
      checklistPackagingDetail: "MSI and NSIS bundles were built successfully.",
    },
  },
  en: {
    overlay: {
      eyebrow: "AI Presence Layer",
      modeIdle: "Idle shell",
      summary:
        "The base overlay is up. The next major block in sequence is secure settings, the audio pipeline, and the Realtime session.",
      hudTitle: "JARVIS // SPEAKING OVERLAY",
      hudSubtitle: "SYSTEMS ONLINE",
      wakeWordLabel: "Wake phrase",
      addressLabel: "Address mode",
      openSettings: "Open settings",
      nextPhase: "Realtime: next phase",
      activateVoice: "Activate voice",
      pauseVoice: "Reset session",
      badgeVoiceLock: "VOICE LOCK",
      badgeLowLatency: "LOW LATENCY",
      badgeMicRequired: "MIC MONITOR",
      badgeSearchReady: "WEB SEARCH READY",
      badgeSecureKeyPending: "SECURE KEY PENDING",
      devIdle: "Idle",
      devListening: "Listening",
      devThinking: "Thinking",
      devSpeaking: "Speaking",
      devReset: "Reset",
      devMicOn: "Mic on",
      devMicOff: "Mic off",
      stateBadge: {
        idle: "IDLE",
        listening: "LISTENING",
        thinking: "THINKING",
        speaking: "SPEAKING",
      },
      statePanels: {
        idle: {
          label: "Overlay state",
          headline: "Standby presence",
          meta: "Awaiting wake phrase or manual activation",
          description: "The HUD stays calm, breathing lightly, and waits for a wake event.",
        },
        listening: {
          label: "Overlay state",
          headline: "Listening for voice input",
          meta: "The microphone analyser is driving the waveform in real time",
          description: "Speak into the microphone. After a short silence, the HUD advances to analysis.",
        },
        thinking: {
          label: "Overlay state",
          headline: "Parsing intent",
          meta: "Transitioning from capture to response synthesis",
          description: "The mask tightens, contours scan, and the assistant briefly holds the turn.",
        },
        speaking: {
          label: "Overlay state",
          headline: "Response presence active",
          meta: "Mask intensity and wave energy increase in speaking mode",
          description: "This state is ready for the future output-audio binding from the realtime session.",
        },
      },
      statusFoundationTitle: "Foundation scaffold",
      statusFoundationDetail: "Tauri 2 + React TS skeleton initialized.",
      statusSettingsTitle: "Settings window",
      statusSettingsDetail: "Programmatic secondary window is wired from Rust.",
      statusKeyTitle: "Secure key storage",
      statusKeyReady: "The OpenAI API key is stored in native secure storage.",
      statusKeyPending: "Windows Credential Manager wiring exists, but no key is stored yet.",
      statusRealtimeTitle: "Realtime voice loop",
      statusRealtimePending: "The WebRTC session flow is the next major integration step.",
    },
    settings: {
      eyebrow: "Configuration / Phase 2",
      title: "JARVIS Control Room",
      summary:
        "Settings now persist on the native side. The next layer in sequence is devices, the Realtime session, and the wake engine.",
      modeChip: "Windows-first",
      profileTitle: "Primary profile",
      profileSummary:
        "These fields now persist across runs. The API key is written to secure native storage and is never returned to the renderer.",
      languageLabel: "Interface language",
      languageRussian: "Russian",
      wakeWordLabel: "Wake word",
      addressLabel: "User address",
      apiKeyLabel: "OpenAI API key",
      apiKeyPlaceholder: "Paste a key to store it securely",
      inlineNote:
        "Language, wake word, and user address now persist. API verification and device settings are the next steps.",
      apiKeyStored: "The API key is already stored in Windows secure storage.",
      apiKeyMissing: "No API key has been stored yet.",
      saveButton: "Save settings",
      closeButton: "Close window",
      executionTitle: "Execution status",
      executionSummary: "Below is the current completion state for foundation and packaging.",
      checklistFoundationTitle: "Tauri desktop scaffold",
      checklistFoundationDetail: "The workspace now contains the first bootable desktop app shell.",
      checklistOverlayTitle: "Separate overlay window",
      checklistOverlayDetail: "The overlay is configured as the main transparent always-on-top window.",
      checklistSettingsTitle: "Separate settings window",
      checklistSettingsDetail: "The settings window is created from Rust and can be focused on demand.",
      checklistTrayTitle: "Tray icon skeleton",
      checklistTrayDetail: "The native tray menu is wired with overlay, settings and quit actions.",
      checklistPackagingTitle: "Production package validation",
      checklistPackagingDetail: "MSI and NSIS bundles were built successfully.",
    },
  },
} as const;

export function getCopy(language: AppLanguage) {
  return copy[language];
}