import type { AppLanguage } from "../types/settings";

const copy = {
  ru: {
    overlay: {
      eyebrow: "Голосовой помощник",
      modeIdle: "Ждет",
      summary:
        "Помощник уже на экране. Дальше по плану: звук ответа, поиск и живой разговор.",
      hudTitle: "ДЖАРВИС",
      hudSubtitle: "Я НА СВЯЗИ",
      wakeWordLabel: "Слово для вызова",
      addressLabel: "Обращение",
      openSettings: "Открыть настройки",
      nextPhase: "Следующий шаг",
      activateVoice: "Начать разговор",
      pauseVoice: "Остановить",
      badgeVoiceLock: "ГОЛОС",
      badgeLowLatency: "БЫСТРЫЙ ОТКЛИК",
      badgeLiveConnection: "ЖИВОЙ РАЗГОВОР",
      badgeMicRequired: "НУЖЕН МИКРОФОН",
      badgeOffline: "НЕТ СЕТИ",
      badgeSearchReady: "ПОИСК ГОТОВ",
      badgeSecureKeyPending: "НУЖЕН КЛЮЧ",
      reconnectClue: "Повторяю подключение",
      devIdle: "Ждет",
      devListening: "Слушает",
      devThinking: "Думает",
      devSpeaking: "Говорит",
      devReset: "Сброс",
      devMicOn: "Микрофон вкл.",
      devMicOff: "Микрофон выкл.",
      devLiveOn: "Связь вкл.",
      devLiveOff: "Связь выкл.",
      youLabel: "Вы",
      jarvisLabel: "Джарвис",
      actionLabel: "Действие",
      errorLabel: "Ошибка",
      actionPrefix: "Выполняю:",
      openConfirmTitle: "Открыть ссылку?",
      openConfirmApprove: "Открыть",
      openConfirmCancel: "Отмена",
      fallbackNoKeyTitle: "Нужен ключ доступа",
      fallbackNoKeyBody: "Откройте настройки и вставьте ключ, чтобы помощник мог говорить с моделью.",
      fallbackMicDeniedTitle: "Нужен доступ к микрофону",
      fallbackMicDeniedBody: "Разрешите приложению пользоваться микрофоном, чтобы помощник мог вас слышать.",
      fallbackMicMissingTitle: "Микрофон недоступен",
      fallbackMicMissingBody: "На этом устройстве не удалось найти работающий микрофон.",
      fallbackOfflineTitle: "Нет связи с интернетом",
      fallbackOfflineBody: "Помощнику нужен интернет, чтобы ответить. Когда связь вернется, можно попробовать снова.",
      fallbackReconnectTitle: "Пытаюсь вернуть связь",
      fallbackOpenSettings: "Открыть настройки",
      fallbackRetry: "Попробовать снова",
      fallbackWait: "Подождать",
      stateBadge: {
        idle: "ЖДЕТ",
        listening: "СЛУШАЕТ",
        thinking: "ДУМАЕТ",
        speaking: "ГОВОРИТ",
        tool: "ДЕЛАЕТ",
        error: "ОШИБКА",
      },
      statePanels: {
        idle: {
          label: "Состояние",
          headline: "Спокойный режим",
          meta: "Ждет слово для вызова или нажатие кнопки",
          description: "Помощник тихо ждет, пока к нему обратятся.",
        },
        listening: {
          label: "Состояние",
          headline: "Слушает вас",
          meta: "Линии двигаются по вашему голосу",
          description: "Говорите в микрофон. Когда вы замолчите, помощник начнет думать.",
        },
        thinking: {
          label: "Состояние",
          headline: "Обдумывает ответ",
          meta: "Сейчас собирает ответ",
          description: "Помощник понял вопрос и готовит короткий ответ.",
        },
        speaking: {
          label: "Состояние",
          headline: "Отвечает",
          meta: "Сейчас звучит ответ модели",
          description: "Когда модель говорит, волна движется по реальному звуку ответа.",
        },
        tool: {
          label: "Состояние",
          headline: "Выполняет просьбу",
          meta: "Сейчас помощник делает нужное действие",
          description: "Если понадобится действие, помощник покажет это здесь простыми словами.",
        },
        error: {
          label: "Состояние",
          headline: "Нужна помощь",
          meta: "Что-то пошло не так",
          description: "Если связь или ключ не подошли, здесь появится понятное сообщение.",
        },
      },
      statusFoundationTitle: "Основа готова",
      statusFoundationDetail: "Главное окно помощника уже работает.",
      statusSettingsTitle: "Настройки готовы",
      statusSettingsDetail: "Окно настроек уже открывается отдельно.",
      statusKeyTitle: "Ключ доступа",
      statusKeyReady: "Ключ сохранен в надежном месте внутри приложения.",
      statusKeyPending: "Ключ еще не сохранен.",
      statusRealtimeTitle: "Живой разговор",
      statusRealtimePending: "Эта часть будет подключена следующей.",
    },
    settings: {
      eyebrow: "Настройки",
      title: "Пульт Джарвиса",
      summary:
        "Здесь можно выбрать язык, слово для вызова и то, как ведет себя окно помощника.",
      modeChip: "Для Windows",
      profileTitle: "Главное",
      profileSummary:
        "Эти настройки сохраняются и остаются после перезапуска приложения.",
      languageLabel: "Язык интерфейса",
      languageRussian: "Русский",
      languageEnglish: "Английский",
      wakeWordLabel: "Слово для вызова",
      addressLabel: "Обращение к пользователю",
      overlayModeLabel: "Как вести себя окну помощника",
      overlayModeQuiet: "Не мешать другим окнам",
      overlayModeFocus: "Показывать поверх окон во время ответа",
      apiKeyLabel: "Ключ доступа",
      apiKeyPlaceholder: "Вставьте ключ, чтобы сохранить его",
      checkKeyButton: "Проверить ключ",
      keyCheckFailed: "Не удалось проверить ключ. Попробуйте еще раз.",
      inputDeviceLabel: "Какой микрофон слушать",
      outputDeviceLabel: "Через что говорить",
      defaultDevice: "Выбирать автоматически",
      microphoneFallback: "Микрофон",
      speakerFallback: "Динамик",
      inlineNote:
        "Сейчас уже сохраняются язык, слово для вызова, имя обращения, поведение окна и выбранные устройства.",
      apiKeyStored: "Ключ уже сохранен.",
      apiKeyMissing: "Ключ еще не сохранен.",
      saveButton: "Сохранить настройки",
      closeButton: "Закрыть окно",
      executionTitle: "Что уже готово",
      executionSummary: "Ниже показано, что уже сделано в приложении.",
      readyBadge: "готово",
      pendingBadge: "позже",
      checklistFoundationTitle: "Запуск приложения",
      checklistFoundationDetail: "Приложение уже можно запустить на компьютере.",
      checklistOverlayTitle: "Окно помощника",
      checklistOverlayDetail: "У помощника есть отдельное прозрачное окно.",
      checklistSettingsTitle: "Окно настроек",
      checklistSettingsDetail: "Настройки открываются в отдельном окне.",
      checklistTrayTitle: "Значок рядом с часами",
      checklistTrayDetail: "У приложения есть значок внизу рядом с системными значками.",
      checklistPackagingTitle: "Готовая сборка",
      checklistPackagingDetail: "Уже собраны установочные файлы для Windows.",
    },
  },
  en: {
    overlay: {
      eyebrow: "AI Presence Layer",
      modeIdle: "Idle shell",
      summary:
        "The base overlay is up. The next major block in sequence is secure settings, the audio pipeline, and the Realtime session.",
      hudTitle: "JARVIS // SPEAKING OVERLAY",
      hudSubtitle: "SYSTEMS ONLINE",
      wakeWordLabel: "Wake phrase",
      addressLabel: "Address mode",
      openSettings: "Open settings",
      nextPhase: "Realtime: next phase",
      activateVoice: "Activate voice",
      pauseVoice: "Reset session",
      badgeVoiceLock: "VOICE LOCK",
      badgeLowLatency: "LOW LATENCY",
      badgeLiveConnection: "LIVE TALK",
      badgeMicRequired: "MIC MONITOR",
      badgeOffline: "OFFLINE",
      badgeSearchReady: "WEB SEARCH READY",
      badgeSecureKeyPending: "SECURE KEY PENDING",
      reconnectClue: "Retrying connection",
      devIdle: "Idle",
      devListening: "Listening",
      devThinking: "Thinking",
      devSpeaking: "Speaking",
      devReset: "Reset",
      devMicOn: "Mic on",
      devMicOff: "Mic off",
      devLiveOn: "Live on",
      devLiveOff: "Live off",
      youLabel: "You",
      jarvisLabel: "Jarvis",
      actionLabel: "Action",
      errorLabel: "Error",
      actionPrefix: "Doing:",
      openConfirmTitle: "Open this link?",
      openConfirmApprove: "Open",
      openConfirmCancel: "Cancel",
      fallbackNoKeyTitle: "An API key is needed",
      fallbackNoKeyBody: "Open settings and add your key so the assistant can talk to the model.",
      fallbackMicDeniedTitle: "Microphone access is needed",
      fallbackMicDeniedBody: "Allow microphone access so the assistant can hear you.",
      fallbackMicMissingTitle: "No microphone is available",
      fallbackMicMissingBody: "This device does not currently provide a working microphone.",
      fallbackOfflineTitle: "No internet connection",
      fallbackOfflineBody: "The assistant needs internet access to answer. Try again when the connection is back.",
      fallbackReconnectTitle: "Trying to restore the connection",
      fallbackOpenSettings: "Open settings",
      fallbackRetry: "Try again",
      fallbackWait: "Wait",
      stateBadge: {
        idle: "IDLE",
        listening: "LISTENING",
        thinking: "THINKING",
        speaking: "SPEAKING",
        tool: "ACTION",
        error: "ERROR",
      },
      statePanels: {
        idle: {
          label: "Overlay state",
          headline: "Standby presence",
          meta: "Awaiting wake phrase or manual activation",
          description: "The HUD stays calm, breathing lightly, and waits for a wake event.",
        },
        listening: {
          label: "Overlay state",
          headline: "Listening for voice input",
          meta: "The microphone analyser is driving the waveform in real time",
          description: "Speak into the microphone. After a short silence, the HUD advances to analysis.",
        },
        thinking: {
          label: "Overlay state",
          headline: "Parsing intent",
          meta: "Transitioning from capture to response synthesis",
          description: "The mask tightens, contours scan, and the assistant briefly holds the turn.",
        },
        speaking: {
          label: "Overlay state",
          headline: "Response presence active",
          meta: "The model is speaking through the live audio stream",
          description: "The waveform now moves using the real answer audio when it is available.",
        },
        tool: {
          label: "Overlay state",
          headline: "Working on a task",
          meta: "The assistant is carrying out an action",
          description: "If the assistant needs to do something, it will show it here in plain language.",
        },
        error: {
          label: "Overlay state",
          headline: "Needs attention",
          meta: "Something went wrong",
          description: "If the connection or key fails, a clear message appears here.",
        },
      },
      statusFoundationTitle: "Foundation scaffold",
      statusFoundationDetail: "Tauri 2 + React TS skeleton initialized.",
      statusSettingsTitle: "Settings window",
      statusSettingsDetail: "Programmatic secondary window is wired from Rust.",
      statusKeyTitle: "Secure key storage",
      statusKeyReady: "The OpenAI API key is stored in native secure storage.",
      statusKeyPending: "Windows Credential Manager wiring exists, but no key is stored yet.",
      statusRealtimeTitle: "Realtime voice loop",
      statusRealtimePending: "The WebRTC session flow is the next major integration step.",
    },
    settings: {
      eyebrow: "Configuration / Phase 2",
      title: "JARVIS Control Room",
      summary:
        "Settings now persist on the native side. The next layer in sequence is devices, the Realtime session, and the wake engine.",
      modeChip: "Windows-first",
      profileTitle: "Primary profile",
      profileSummary:
        "These fields now persist across runs. The API key is written to secure native storage and is never returned to the renderer.",
      languageLabel: "Interface language",
      languageRussian: "Russian",
      languageEnglish: "English",
      wakeWordLabel: "Wake word",
      addressLabel: "User address",
      overlayModeLabel: "How the helper window should behave",
      overlayModeQuiet: "Do not cover other windows",
      overlayModeFocus: "Show above windows while answering",
      apiKeyLabel: "OpenAI API key",
      apiKeyPlaceholder: "Paste a key to store it securely",
      checkKeyButton: "Check key",
      keyCheckFailed: "Could not check the key. Please try again.",
      inputDeviceLabel: "Microphone to listen to",
      outputDeviceLabel: "Speaker for answers",
      defaultDevice: "Choose automatically",
      microphoneFallback: "Microphone",
      speakerFallback: "Speaker",
      inlineNote:
        "Language, wake word, user address, window behavior and selected devices now persist.",
      apiKeyStored: "The API key is already stored in Windows secure storage.",
      apiKeyMissing: "No API key has been stored yet.",
      saveButton: "Save settings",
      closeButton: "Close window",
      executionTitle: "Execution status",
      executionSummary: "Below is the current completion state for foundation and packaging.",
      readyBadge: "done",
      pendingBadge: "later",
      checklistFoundationTitle: "Tauri desktop scaffold",
      checklistFoundationDetail: "The workspace now contains the first bootable desktop app shell.",
      checklistOverlayTitle: "Separate overlay window",
      checklistOverlayDetail: "The overlay is configured as the main transparent always-on-top window.",
      checklistSettingsTitle: "Separate settings window",
      checklistSettingsDetail: "The settings window is created from Rust and can be focused on demand.",
      checklistTrayTitle: "Tray icon skeleton",
      checklistTrayDetail: "The native tray menu is wired with overlay, settings and quit actions.",
      checklistPackagingTitle: "Production package validation",
      checklistPackagingDetail: "MSI and NSIS bundles were built successfully.",
    },
  },
} as const;

export function getCopy(language: AppLanguage) {
  return copy[language];
}